config/routes.rb
SampleApp::Application.routes.draw do

  get "users/new"

  root :to => 'pages#home'

  match 'signup',  :to => 'users#new'
  match 'help',    :to => 'pages#help'
  match 'about',   :to => 'pages#about'
  match 'contact', :to => 'pages#contact'











end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "home"
  end

  def contact
    @title = "contact"
  end

  def about
    @title = "about"
  end
  def help
    @title = "help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Ruby On Rails tutorial application"
    if @title.nil?
    base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  def logo
    image_tag("logo.png", :alt => "Sample app logo", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "About", about_path%>
			</li>
			<li>
				<%= link_to "Contact", contact_path%>
			</li>
			<li>
				<%= link_to "BBC",'http://bbcpersian.com'%>
			</li>
			<li>
				<%= link_to "Tweeter",'http://web.tweetdeck.com'%>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path%>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path%>
			</li>
			<li>
				<%= link_to "Help", help_path%>
			</li>
			<li>
				<%= link_to "Sign in",'#'%>
			</li>

		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<!--[if lt IE 9]>
<%= stylesheet_link_tag 'blueprint/ie'%>
<![endif]-->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print'%>
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<title><%= title%></title>
		<%= csrf_meta_tag%>
		<%= render 'layouts/stylesheets'%>
	</head>
	<body>
		<div id="container" class="container">
			<%= render 'layouts/header'%>

			<section class="round" >
				<%= yield%>
			</section>
			<%= render 'layouts/footer'%>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>This is a tutorial example</h1>

app/views/pages/contact.html.erb
<h1>
	You can contact me via <a target="_blank" href="http://aakpro@gmail.com">this</a> email
</h1>

app/views/pages/help.html.erb
<h1>This is help page just tell me ;) </h1>

app/views/pages/home.html.erb
<%= link_to "Sign up now!",users_new_path,:class=>"signup_button round" %> 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>